---
- hosts: cumulus 
  sudo: yes
  tasks:
  - name: Copy Interfaces File 
    copy: src={{ inventory_hostname }}/interfaces dest=/etc/network/interfaces  
    notify:
    - apply interfaces
  - name: Set Hostname
    hostname: name={{ inventory_hostname }} 
  - name: enable BGP in Quagga Daemons
    cl_quagga_protocol: name="bgpd" state="present"
    notify:
    - restart quagga

  handlers:
   - name: apply interfaces
     command: ifreload -a
   - name: restart quagga
     command: name=quagga state=restarted
